name: KiCS scan
permissions:
  contents: read
  actions: read
  security-events: write
  
on:
  workflow_dispatch:

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: checkmarx/kics-github-action@05aa5eb70eede1355220f4ca5238d96b397e30a6 #v2.1.20
        with:
          path: '.github/workflows'
          platform_type: cicd
          queries: 'assets/queries/cicd/github'
          exclude_queries: 555ab8f9-2001-455e-a077-f2d0f41e2fb9
          disable_secrets: true
          ignore_on_exit: results
          output_path: results-dir
          output_formats: json,sarif
      - name: display kics results
        run: |
          cat results-dir/results.json
          # optionally parse the results with jq
          # jq '"# results: \(.total_counter)"' results-dir/results.json
          # jq '"# queries run: \(.queries_total)"' results-dir/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225  #v4
        with:
          sarif_file: results-dir/results.sarif
